### ISSUE TITLE
Need to be able to create users

### ISSUE THREAD

**Issue by leslieharland** [maxtoroq/MvcAccount#10]
How do I do that?

**Comment by lesliechen5705** [comment]
I know that I can add on directly to the static list, but how does the customize what happens during authentication? For example, I would want to query the database for the user with user id and password and login when credentials are correctly entered.

**Comment by maxtoroq** [comment]
Creating user accounts is out of the scope of this library. There are several components that can help you do it, e.g. you can use MvcAccount.PasswordLengthAttribute to validate password length on your model, MvcAccount.AccountRepository to check if username/email already exists, MvcAccount.PasswordService to encrypt the password for storage, MvcAccount.FormsAuthenticationService if you'd like to authenticate user immediately after signup.
